### ISSUE TITLE
How to add images properly?

### ISSUE THREAD

**Issue by ghost** [buoyantair/faraco-profile#1]
Is there a specific way to do this?

**Comment by elevenpassin** [comment]
Hey @faraco ! yes there's a way

**Comment by ghost** [comment]
Hey @buoyantair! I already sent you a few messages on Gitter if you did not check it yet.

Do you mind to share the instructions (or putting them into README.md for everybody else reference) ?

As you can see, it's been six to seven months since the last time I issued the project. I forgot how it works, to be honest.

**Comment by ghost** [comment]
Hello again, can I get at least the compilation steps. I'm totally lost.
